name: simnibs_env
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.9.12
  - numpy=1.22.0
  - scipy=1.9
  - h5py=3.6.0
  - pyopengl=3.1.1a1
  - pytest=7.1.1
  - cython=0.29.28
  - mock=4.0.3
  - packaging=21.3
  - requests=2.27.1
  - freeglut=3.0.0
  - vs2015_runtime=14.27.29016
  - pip=21.2.4
  - matplotlib=3.5.1
  - boost=1.73.0
  - tbb=2021.5.0
  - libwebp=1.2.2
  - pillow=9.0.1
  - nibabel=3.2.2
  - pyqt=5.9.2
  - mkl=2021.4.0
  - jsonschema=4.17.3
  - pip:
    - atomicwrites==1.4.0
    - attrs==23.1.0
    - Brotli==1.0.9
    - build==1.2.2.post1
    - certifi==2024.8.30
    - cffi==1.16.0
    - charm-gems==1.3
    - charset-normalizer==2.0.4
    - click==8.1.7
    - colorama==0.4.6
    - cryptography==41.0.3
    - cupy-cuda113==10.6.0
    - cycler==0.11.0
    - Cython==0.29.28
    - fastrlock==0.8.2
    - fmm3dpy==1.0.0
    - fonttools==4.51.0
    - func_timeout==4.3.5
    - geneticalgorithm==1.0.2
    - h5py==3.6.0
    - idna==3.7
    - importlib_metadata==8.5.0
    - iniconfig==1.1.1
    - jsonschema==4.17.3
    - kiwisolver==1.4.4
    - matplotlib==3.5.1
    - mkl-service==2.4.0
    - mock==4.0.3
    - nibabel==3.2.2
    - numpy==1.22.0
    - packaging==21.3
    - Pillow==9.0.1
    - pip==24.3.1
    - pip-tools==7.4.1
    - pluggy==1.0.0
    - py==1.11.0
    - pycparser==2.21
    - pydicom==2.4.4
    - PyOpenGL==3.1.1a1
    - pyOpenSSL==23.2.0
    - pyparsing==3.1.2
    - pyproject_hooks==1.2.0
    - PyQt5==5.15.11
    - PyQt5-Qt5==5.15.2
    - PyQt5_sip==12.15.0
    - pyreadline==2.1
    - pyrsistent==0.20.0
    - PySocks==1.7.1
    - pytest==7.1.1
    - python-dateutil==2.9.0.post0
    - pytz==2024.2
    - PyYAML==6.0.2
    - requests==2.27.1
    - scikit-opt==0.6.6
    - scipy==1.9.3
    - setuptools==70.0.0
    - simnibs==4.1.0
    - sip==4.19.13
    - six==1.16.0
    - tomli==2.0.1
    - tornado==6.3.3
    - tqdm==4.66.5
    - tzdata==2024.2
    - unicodedata2==15.1.0
    - urllib3==1.26.19
    - wheel==0.44.0
    - win-inet-pton==1.1.0
    - zipp==3.20.2

